In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame({
    "Name": ["Sajin","Aaron","Lijin"],
    "Age":[23,22,21],
    "Gender":["Male","Male","Male"],

})

In [15]:
df

    Name  Age Gender
0  Sajin   23   Male
1  Aaron   22   Male
2  Lijin   21   Male

In [16]:
df["Age"]

0    23
1    22
2    21
Name: Age, dtype: int64

In [17]:
df["Name"]

0    Sajin
1    Aaron
2    Lijin
Name: Name, dtype: object

In [19]:
df["Gender"]

0    Male
1    Male
2    Male
Name: Gender, dtype: object

In [20]:
df["Age"].max()

23

In [21]:
df["Age"].min()

21

In [22]:
df.describe()

        Age
count   3.0
mean   22.0
std     1.0
min    21.0
25%    21.5
50%    22.0
75%    22.5
max    23.0