In [3]:
# Subset of a DataFrame
import pandas as pd

In [4]:
titanic = pd.read_csv("/Users/sajin/Datasets/tested.csv")

In [5]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
ages = titanic["Age"]

In [12]:
ages

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ...
413     NaN
414    39.0
415    38.5
416     NaN
417     NaN
Name: Age, Length: 418, dtype: float64

In [13]:
type(ages)

pandas.core.series.Series

In [14]:
ages.shape

(418,)

In [15]:
titanic["Age"].shape

(418,)

In [16]:
name_age = titanic[["Name","Age"]]

In [17]:
name_age

                                             Name   Age
0                                Kelly, Mr. James  34.5
1                Wilkes, Mrs. James (Ellen Needs)  47.0
2                       Myles, Mr. Thomas Francis  62.0
3                                Wirz, Mr. Albert  27.0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0
..                                            ...   ...
413                            Spector, Mr. Woolf   NaN
414                  Oliva y Ocana, Dona. Fermina  39.0
415                  Saether, Mr. Simon Sivertsen  38.5
416                           Ware, Mr. Frederick   NaN
417                      Peter, Master. Michael J   NaN

[418 rows x 2 columns]

In [18]:
type(name_age)

pandas.core.frame.DataFrame

In [19]:
above_35 = titanic[titanic["Age"] > 35]

In [23]:
above_35.info()

<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 1 to 415
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  105 non-null    int64
 1   Survived     105 non-null    int64
 2   Pclass       105 non-null    int64
 3   Name         105 non-null    object
 4   Sex          105 non-null    object
 5   Age          105 non-null    float64
 6   SibSp        105 non-null    int64
 7   Parch        105 non-null    int64
 8   Ticket       105 non-null    object
 9   Fare         104 non-null    float64
 10  Cabin        51 non-null     object
 11  Embarked     105 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 10.7+ KB

In [24]:
above_40 = titanic["Age"] > 40

In [25]:
above_40

0      False
1       True
2       True
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Name: Age, Length: 418, dtype: bool

In [26]:
type(above_40)

pandas.core.series.Series

In [28]:
above_40.info()

<class 'pandas.core.series.Series'>
RangeIndex: 418 entries, 0 to 417
Series name: Age
Non-Null Count  Dtype
--------------  -----
418 non-null    bool
dtypes: bool(1)
memory usage: 550.0 bytes

In [29]:
titanic["Age"] > 35

0      False
1       True
2       True
3      False
4      False
       ...
413    False
414     True
415     True
416    False
417    False
Name: Age, Length: 418, dtype: bool

In [31]:
above_40.shape

(418,)

In [32]:
above_35.shape

(105, 12)

In [34]:
type(above_35)

pandas.core.frame.DataFrame

In [38]:
unique_pclass = titanic["Pclass"]

In [39]:
unique_pclass

0      3
1      3
2      2
3      3
4      3
      ..
413    3
414    1
415    3
416    3
417    3
Name: Pclass, Length: 418, dtype: int64

In [40]:
unique_pclass = titanic["Pclass"].unique()

In [41]:
unique_pclass

array([3, 2, 1])

In [43]:
class_12 = titanic[titanic['Pclass'].isin([1,2])]

In [45]:
class_12.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S

In [46]:
class_12.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 2 to 414
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Survived     200 non-null    int64
 2   Pclass       200 non-null    int64
 3   Name         200 non-null    object
 4   Sex          200 non-null    object
 5   Age          186 non-null    float64
 6   SibSp        200 non-null    int64
 7   Parch        200 non-null    int64
 8   Ticket       200 non-null    object
 9   Fare         200 non-null    float64
 10  Cabin        87 non-null     object
 11  Embarked     200 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 20.3+ KB

In [52]:
age_no_na = titanic["Age"].notna()

In [53]:
age_no_na

0       True
1       True
2       True
3       True
4       True
       ...
413    False
414     True
415     True
416    False
417    False
Name: Age, Length: 418, dtype: bool